char SUPLA_WIFI_SSID[20]="";
char SUPLA_WIFI_PASS[50]="";
char SUPLA_EMAIL[50]="";
char SUPLA_SVR[50]="";

char GUID[SUPLA_GUID_SIZE] = {0xA4};
char AUTHKEY[SUPLA_AUTHKEY_SIZE] = {0x09};
int ZG_OPEN_NETWORK=20;

