name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: PlatformIO platform installation
        run: pio pkg install
      - name: Update .platformio\platforms\espressif32\boards\esp32-c6-devkitc-1.json file to enable arduino framework
        if: always()
        uses: restackio/update-json-file-action@2.1
        with:
          file: /home/runner/.platformio/platforms/espressif32/boards/esp32-c6-devkitc-1.json
          fields: "{\"frameworks[0]\": \"arduino\", \"build.variant\": \"esp32c6\"}"
      - name: Build PlatformIO Project
        run: pio run
